### ISSUE TITLE
fix: breathing animation doesn't display on certain websites

### ISSUE THREAD

**Issue by qu8n** [qu8n/arc-boost-mindful-media#1]
Examples include www.linkedin.com and www.instagram.com.

**Comment by rezaarkan** [comment]
I changed the css animation name from `pulse` to `mm-pulse` to avoid naming conflicts for the injected website. Seems to have worked for both Instagram and Linkedin. See #5

**Comment by qu8n** [comment]
Great catch! I left a a few follow-up questions in your PR. Looking forward to clarifying my questions and merging your changes.

**Comment by qu8n** [comment]
Resolved by #5
